In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report
import re
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
fake = pd.read_csv("data/Fake.csv")
fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [3]:
fake["label"] = 1
fake

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [4]:
real = pd.read_csv("data/True.csv")

In [5]:
real

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [6]:
real["label"] = 0
real

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [7]:
data = pd.concat([real, fake ],axis=0)

In [8]:
data

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [9]:
data = data.sample(frac=1)

In [10]:
data.head(10)

,title,text,subject,date,label
14411,No deal on tax among German coalition parties:...,BERLIN (Reuters) - Germany s would-be coalitio...,worldnews,"November 19, 2017",0
39,This Sarah Huckabee Sanders Tweet About Attac...,"Donald J. Trump spent a portion of his Sunday,...",News,"December 4, 2017",1
12301,In-flight sexual assaults often unreported; ai...,SINGAPORE/NEW DELHI (Reuters) - When a 17-yea...,worldnews,"December 14, 2017",0
13745,LIBERAL HEADS EXPLODE When PIERS MORGAN Points...,Watch the video and you be the judge. Was Pier...,politics,"Jun 6, 2016",1
20674,Pope says Colombia must confront inequality to...,BOGOTA (Reuters) - Pope Francis on Thursday ur...,worldnews,"September 7, 2017",0
19254,"New Zealand's ruling Nationals win most votes,...",WELLINGTON (Reuters) - New Zealand s ruling Na...,worldnews,"September 22, 2017",0
20215,New Slovak education minister appointed after ...,BRATISLAVA (Reuters) - Slovakia s president ap...,worldnews,"September 13, 2017",0
790,House tax panel chair says expects vote on pla...,WASHINGTON (Reuters) - U.S. House Republicans ...,politicsNews,"November 7, 2017",0
13184,Trump still weighing whether to recognize Jeru...,WASHINGTON (Reuters) - U.S. President Donald T...,worldnews,"December 3, 2017",0
14432,CUCKOO! BERNIE SANDERS SUPPORTER Gets Hammered...,Stuart Varney hammers a cuckoo super delegate ...,politics,"Feb 22, 2016",1

In [11]:
data.tail(10)

,title,text,subject,date,label
4180,BREAKING: Sheriff Calls For REBELLION After D...,"As Donald Trump s poll numbers drop, he contin...",News,"October 15, 2016",1
10796,TRIGGERED! FORMER CIA AGENT: ‘Trey Gowdy Ought...,Former CIA Agent Phil Mudd is a jackwagon! He ...,politics,"May 24, 2017",1
4276,"Russia and USA, after Tillerson talks, agree m...",MOSCOW (Reuters) - Russia and the United State...,politicsNews,"April 12, 2017",0
14452,HOW PRESIDENT EISENHOWER Solved The Illegal Im...,"Since this article was written in 2006, the il...",politics,"Feb 19, 2016",1
1434,Foreign government code reviews 'problematic':...,WASHINGTON (Reuters) - Allowing foreign govern...,politicsNews,"October 3, 2017",0
2909,Illinois governor announces veto of $5 billion...,CHICAGO (Reuters) - Illinois Governor Bruce Ra...,politicsNews,"July 4, 2017",0
11643,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,,politics,"Feb 16, 2017",1
22833,Boiler Room EP #120 – Scorched Earth Media: Fr...,Tune in to the Alternate Current Radio Network...,Middle-east,"August 4, 2017",1
10643,THE VIEW DINGBATS Descend On Faux Conservative...,Anti-Trumper and faux conservative Jedediah Bi...,politics,"Jun 12, 2017",1
5838,Trump Epically Owned Himself In A Tweet And T...,Donald Trump tweets out a number of terrible o...,News,"June 17, 2016",1

In [12]:
data = data.drop(["title","subject","date"],axis=1)

In [13]:
data

                                                    text  label
14411  BERLIN (Reuters) - Germany s would-be coalitio...      0
39     Donald J. Trump spent a portion of his Sunday,...      1
12301   SINGAPORE/NEW DELHI (Reuters) - When a 17-yea...      0
13745  Watch the video and you be the judge. Was Pier...      1
20674  BOGOTA (Reuters) - Pope Francis on Thursday ur...      0
...                                                  ...    ...
2909   CHICAGO (Reuters) - Illinois Governor Bruce Ra...      0
11643                                                         1
22833  Tune in to the Alternate Current Radio Network...      1
10643  Anti-Trumper and faux conservative Jedediah Bi...      1
5838   Donald Trump tweets out a number of terrible o...      1

[44898 rows x 2 columns]

In [14]:
data.isnull().sum()

text     0
label    0
dtype: int64

In [15]:
def word_drop(text):
    text = text.lower()
    text = re.sub('\[.*?\]','',text)
    text = re.sub("\\W" ," ", text)
    text = re.sub('https?://\S+|www.\.\S+','',text)
    text = re.sub('<.*?>+' , '',text)
    text = re.sub('\n','',text)
    text = re.sub('\w*\d\w','',text)
    return text

In [16]:
data['text'] = data['text'].apply(word_drop)

In [17]:
sample_data = data.head(10).to_csv("sample.csv")
sample_data

In [18]:
x = data["text"]
y = data["label"]

In [19]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size=.25)

In [20]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

##### Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
LRmodel = LogisticRegression()

In [23]:
LRmodel.fit(xv_train ,y_train  )
LRmodel.score(xv_test ,y_test  )

0.9846770601336303

In [24]:
Pred_LR = LRmodel.predict(xv_test)
print(classification_report(y_test,Pred_LR))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98      5340
           1       0.99      0.98      0.99      5885

    accuracy                           0.98     11225
   macro avg       0.98      0.98      0.98     11225
weighted avg       0.98      0.98      0.98     11225

###### Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
DTmodel = DecisionTreeClassifier()
DTmodel.fit(xv_train ,y_train)
DTmodel.score(xv_test ,y_test  )

0.995902004454343

In [26]:
Pred_DT = DTmodel.predict(xv_test)
print(classification_report(y_test,Pred_DT))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5340
           1       1.00      1.00      1.00      5885

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

###### Gradient Boost

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [28]:
GBmodel = GradientBoostingClassifier(random_state=0)
GBmodel.fit(xv_train ,y_train)
GBmodel.score(xv_test ,y_test  )

0.9958129175946547

In [29]:
Pred_GB = GBmodel.predict(xv_test)
print(classification_report(y_test,Pred_GB))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      5340
           1       1.00      0.99      1.00      5885

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

###### Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
RFmodel = RandomForestClassifier(random_state=0)
RFmodel.fit(xv_train ,y_train)
RFmodel.score(xv_test ,y_test  )

0.987706013363029

In [32]:
Pred_RF = RFmodel.predict(xv_test)
print(classification_report(y_test,Pred_RF))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5340
           1       0.99      0.99      0.99      5885

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225